# Generated by Django 2.1.3 on 2018-12-16 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_browser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb_src',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
    ]
