# Generated by Django 2.1.3 on 2018-12-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_browser', '0002_image_thumb_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLikeCount',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'image_likes',
                'managed': False,
            },
        ),
    ]
