# Generated by Django 2.1.3 on 2019-01-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_browser', '0003_imagelikecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(default='', max_length=128),
        ),
    ]
