# Generated by Django 2.1.3 on 2019-02-24 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('image_browser', '0004_image_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.IntegerField()),
                ('tags', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=False)),
                ('create_time',models.DateTimeField(default=datetime.datetime(2019, 1, 12, 8, 21, 6, 107656, tzinfo=utc))),
            ],
            options={
                'db_table': 'image_tags',
            },
        ),
    ]
