# Generated by Django 2.1.3 on 2019-01-12 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_browser', '0003_imagelikecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='image_browser.Image')),
            ],
            options={
                'db_table': 'collect_images',
            },
        ),
        migrations.CreateModel(
            name='InvitationCodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'invitation_code',
            },
        ),
        migrations.CreateModel(
            name='MailCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('update_time', models.DateTimeField(default=datetime.datetime(2019, 1, 12, 8, 21, 6, 109711, tzinfo=utc))),
            ],
            options={
                'db_table': 'mail_code',
            },
        ),
        migrations.CreateModel(
            name='UserLoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('user_agent', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12)),
                ('avatar', models.URLField()),
                ('age', models.IntegerField(default=0)),
                ('gender', models.IntegerField(default=0)),
                ('mobile', models.CharField(max_length=11)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 1, 12, 8, 21, 6, 107656, tzinfo=utc))),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('invite', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='userloginmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel'),
        ),
        migrations.AddField(
            model_name='collectimagesmodel',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.UserModel'),
        ),
        migrations.AlterUniqueTogether(
            name='collectimagesmodel',
            unique_together={('user', 'image')},
        ),
    ]
