# Generated by Django 2.1.3 on 2019-01-23 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectimagesmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 6, 6, 30, 862541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mailcodemodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 6, 6, 30, 863007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 6, 6, 30, 861370, tzinfo=utc)),
        ),
    ]
